# Generated by Django 5.1.3 on 2025-01-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_keyword_alter_restaurant_options_restaurant_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': '키워드', 'verbose_name_plural': '키워드 모음'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-rating'], 'verbose_name': '가게', 'verbose_name_plural': '가게들'},
        ),
        migrations.AlterModelOptions(
            name='restaurantstatistics',
            options={'verbose_name': '가게 통계', 'verbose_name_plural': '가게 통계 집합'},
        ),
    ]
