# Generated by Django 5.1.3 on 2025-01-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_keyword_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
            ],
            options={
                'verbose_name': '가게 카테고리',
                'verbose_name_plural': '가게 카테고리',
            },
        ),
    ]
