# Generated by Django 5.1.3 on 2025-01-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_category_alter_restaurant_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
    ]
