# Generated by Django 5.1.3 on 2025-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_keyword_restaurantcategory_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='RestaurantCategory',
        ),
        migrations.RemoveField(
            model_name='restaurantstatistics',
            name='restaurant',
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='RestaurantStatistics',
        ),
    ]
